//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.22 at 06:02:21 AM IST 
//


package soap.services;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for bankers complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="bankers">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bankerId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="bankerName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="bankerPasscode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bankers", propOrder = {
    "bankerId",
    "bankerName",
    "bankerPasscode"
})
public class Bankers {

    protected int bankerId;
    @XmlElement(required = true)
    protected String bankerName;
    @XmlElement(required = true)
    protected String bankerPasscode;

    /**
     * Gets the value of the bankerId property.
     * 
     */
    public int getBankerId() {
        return bankerId;
    }

    /**
     * Sets the value of the bankerId property.
     * 
     */
    public void setBankerId(int value) {
        this.bankerId = value;
    }

    /**
     * Gets the value of the bankerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankerName() {
        return bankerName;
    }

    /**
     * Sets the value of the bankerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankerName(String value) {
        this.bankerName = value;
    }

    /**
     * Gets the value of the bankerPasscode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankerPasscode() {
        return bankerPasscode;
    }

    /**
     * Sets the value of the bankerPasscode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankerPasscode(String value) {
        this.bankerPasscode = value;
    }

}
