//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.22 at 06:02:21 AM IST 
//


package soap.services;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the soap.services package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: soap.services
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetByIdResponse }
     * 
     */
    public GetByIdResponse createGetByIdResponse() {
        return new GetByIdResponse();
    }

    /**
     * Create an instance of {@link Bankers }
     * 
     */
    public Bankers createBankers() {
        return new Bankers();
    }

    /**
     * Create an instance of {@link ListBankersRequest }
     * 
     */
    public ListBankersRequest createListBankersRequest() {
        return new ListBankersRequest();
    }

    /**
     * Create an instance of {@link DeleteViaIdResponse }
     * 
     */
    public DeleteViaIdResponse createDeleteViaIdResponse() {
        return new DeleteViaIdResponse();
    }

    /**
     * Create an instance of {@link ServiceStatus }
     * 
     */
    public ServiceStatus createServiceStatus() {
        return new ServiceStatus();
    }

    /**
     * Create an instance of {@link ListBankersResponse }
     * 
     */
    public ListBankersResponse createListBankersResponse() {
        return new ListBankersResponse();
    }

    /**
     * Create an instance of {@link DeleteViaIdRequest }
     * 
     */
    public DeleteViaIdRequest createDeleteViaIdRequest() {
        return new DeleteViaIdRequest();
    }

    /**
     * Create an instance of {@link NewBankersRequest }
     * 
     */
    public NewBankersRequest createNewBankersRequest() {
        return new NewBankersRequest();
    }

    /**
     * Create an instance of {@link NewBankersResponse }
     * 
     */
    public NewBankersResponse createNewBankersResponse() {
        return new NewBankersResponse();
    }

    /**
     * Create an instance of {@link GetByIdRequest }
     * 
     */
    public GetByIdRequest createGetByIdRequest() {
        return new GetByIdRequest();
    }

}
